//! `SeaORM` Entity, @generated by sea-orm-codegen 0.1.0

use super::sea_orm_active_enums::ClaimItemReasonEnum;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "claim_item")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: String,
	pub claim_order_id: String,
	pub item_id: String,
	pub variant_id: String,
	pub reason: ClaimItemReasonEnum,
	pub note: Option<String>,
	pub quantity: i32,
	pub created_at: DateTimeWithTimeZone,
	pub updated_at: DateTimeWithTimeZone,
	pub deleted_at: Option<DateTimeWithTimeZone>,
	#[sea_orm(column_type = "JsonBinary", nullable)]
	pub metadata: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::claim_image::Entity")]
	ClaimImage,
	#[sea_orm(has_many = "super::claim_item_tags::Entity")]
	ClaimItemTags,
	#[sea_orm(
		belongs_to = "super::claim_order::Entity",
		from = "Column::ClaimOrderId",
		to = "super::claim_order::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	ClaimOrder,
	#[sea_orm(
		belongs_to = "super::line_item::Entity",
		from = "Column::ItemId",
		to = "super::line_item::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	LineItem,
	#[sea_orm(
		belongs_to = "super::product_variant::Entity",
		from = "Column::VariantId",
		to = "super::product_variant::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	ProductVariant,
}

impl Related<super::claim_image::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ClaimImage.def()
	}
}

impl Related<super::claim_item_tags::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ClaimItemTags.def()
	}
}

impl Related<super::claim_order::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ClaimOrder.def()
	}
}

impl Related<super::line_item::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::LineItem.def()
	}
}

impl Related<super::product_variant::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ProductVariant.def()
	}
}

impl Related<super::claim_tag::Entity> for Entity {
	fn to() -> RelationDef {
		super::claim_item_tags::Relation::ClaimTag.def()
	}
	fn via() -> Option<RelationDef> {
		Some(super::claim_item_tags::Relation::ClaimItem.def().rev())
	}
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
	#[sea_orm(entity = "super::claim_image::Entity")]
	ClaimImage,
	#[sea_orm(entity = "super::claim_item_tags::Entity")]
	ClaimItemTags,
	#[sea_orm(entity = "super::claim_order::Entity")]
	ClaimOrder,
	#[sea_orm(entity = "super::line_item::Entity")]
	LineItem,
	#[sea_orm(entity = "super::product_variant::Entity")]
	ProductVariant,
	#[sea_orm(entity = "super::claim_tag::Entity")]
	ClaimTag,
}
