//! `SeaORM` Entity, @generated by sea-orm-codegen 0.1.0

use super::sea_orm_active_enums::ClaimOrderFulfillmentStatusEnum;
use super::sea_orm_active_enums::ClaimOrderPaymentStatusEnum;
use super::sea_orm_active_enums::ClaimOrderTypeEnum;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "claim_order")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: String,
	pub payment_status: ClaimOrderPaymentStatusEnum,
	pub fulfillment_status: ClaimOrderFulfillmentStatusEnum,
	pub r#type: ClaimOrderTypeEnum,
	pub order_id: String,
	pub shipping_address_id: Option<String>,
	pub refund_amount: Option<i32>,
	pub canceled_at: Option<DateTimeWithTimeZone>,
	pub created_at: DateTimeWithTimeZone,
	pub updated_at: DateTimeWithTimeZone,
	pub deleted_at: Option<DateTimeWithTimeZone>,
	#[sea_orm(column_type = "JsonBinary", nullable)]
	pub metadata: Option<Json>,
	pub idempotency_key: Option<String>,
	pub no_notification: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::address::Entity",
		from = "Column::ShippingAddressId",
		to = "super::address::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Address,
	#[sea_orm(has_many = "super::claim_item::Entity")]
	ClaimItem,
	#[sea_orm(has_many = "super::fulfillment::Entity")]
	Fulfillment,
	#[sea_orm(has_many = "super::line_item::Entity")]
	LineItem,
	#[sea_orm(
		belongs_to = "super::order::Entity",
		from = "Column::OrderId",
		to = "super::order::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Order,
	#[sea_orm(has_one = "super::r#return::Entity")]
	Return,
	#[sea_orm(has_many = "super::shipping_method::Entity")]
	ShippingMethod,
}

impl Related<super::address::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Address.def()
	}
}

impl Related<super::claim_item::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ClaimItem.def()
	}
}

impl Related<super::fulfillment::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Fulfillment.def()
	}
}

impl Related<super::line_item::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::LineItem.def()
	}
}

impl Related<super::order::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Order.def()
	}
}

impl Related<super::r#return::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Return.def()
	}
}

impl Related<super::shipping_method::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ShippingMethod.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
	#[sea_orm(entity = "super::address::Entity")]
	Address,
	#[sea_orm(entity = "super::claim_item::Entity")]
	ClaimItem,
	#[sea_orm(entity = "super::fulfillment::Entity")]
	Fulfillment,
	#[sea_orm(entity = "super::line_item::Entity")]
	LineItem,
	#[sea_orm(entity = "super::order::Entity")]
	Order,
	#[sea_orm(entity = "super::r#return::Entity")]
	Return,
	#[sea_orm(entity = "super::shipping_method::Entity")]
	ShippingMethod,
}
