//! `SeaORM` Entity, @generated by sea-orm-codegen 0.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "discount_condition_customer_group")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub customer_group_id: String,
	#[sea_orm(primary_key, auto_increment = false)]
	pub condition_id: String,
	pub created_at: DateTimeWithTimeZone,
	pub updated_at: DateTimeWithTimeZone,
	#[sea_orm(column_type = "JsonBinary", nullable)]
	pub metadata: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::customer_group::Entity",
		from = "Column::CustomerGroupId",
		to = "super::customer_group::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	CustomerGroup,
	#[sea_orm(
		belongs_to = "super::discount_condition::Entity",
		from = "Column::ConditionId",
		to = "super::discount_condition::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	DiscountCondition,
}

impl Related<super::customer_group::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::CustomerGroup.def()
	}
}

impl Related<super::discount_condition::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::DiscountCondition.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
	#[sea_orm(entity = "super::customer_group::Entity")]
	CustomerGroup,
	#[sea_orm(entity = "super::discount_condition::Entity")]
	DiscountCondition,
}
