//! `SeaORM` Entity, @generated by sea-orm-codegen 0.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "fulfillment_provider")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: String,
	pub is_installed: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::fulfillment::Entity")]
	Fulfillment,
	#[sea_orm(has_many = "super::region_fulfillment_providers::Entity")]
	RegionFulfillmentProviders,
	#[sea_orm(has_many = "super::shipping_option::Entity")]
	ShippingOption,
}

impl Related<super::fulfillment::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Fulfillment.def()
	}
}

impl Related<super::region_fulfillment_providers::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::RegionFulfillmentProviders.def()
	}
}

impl Related<super::shipping_option::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ShippingOption.def()
	}
}

impl Related<super::region::Entity> for Entity {
	fn to() -> RelationDef {
		super::region_fulfillment_providers::Relation::Region.def()
	}
	fn via() -> Option<RelationDef> {
		Some(super::region_fulfillment_providers::Relation::FulfillmentProvider.def().rev())
	}
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
	#[sea_orm(entity = "super::fulfillment::Entity")]
	Fulfillment,
	#[sea_orm(entity = "super::region_fulfillment_providers::Entity")]
	RegionFulfillmentProviders,
	#[sea_orm(entity = "super::shipping_option::Entity")]
	ShippingOption,
	#[sea_orm(entity = "super::region::Entity")]
	Region,
}
