//! `SeaORM` Entity, @generated by sea-orm-codegen 0.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "fulfillment_item")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub fulfillment_id: String,
	#[sea_orm(primary_key, auto_increment = false)]
	pub item_id: String,
	pub quantity: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::fulfillment::Entity",
		from = "Column::FulfillmentId",
		to = "super::fulfillment::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Fulfillment,
	#[sea_orm(
		belongs_to = "super::line_item::Entity",
		from = "Column::ItemId",
		to = "super::line_item::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	LineItem,
}

impl Related<super::fulfillment::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Fulfillment.def()
	}
}

impl Related<super::line_item::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::LineItem.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
	#[sea_orm(entity = "super::fulfillment::Entity")]
	Fulfillment,
	#[sea_orm(entity = "super::line_item::Entity")]
	LineItem,
}
