//! `SeaORM` Entity, @generated by sea-orm-codegen 0.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "gift_card_transaction")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: String,
	pub gift_card_id: String,
	pub order_id: String,
	pub amount: i32,
	pub created_at: DateTimeWithTimeZone,
	pub is_taxable: Option<bool>,
	#[sea_orm(column_type = "Float", nullable)]
	pub tax_rate: Option<f32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::gift_card::Entity",
		from = "Column::GiftCardId",
		to = "super::gift_card::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	GiftCard,
	#[sea_orm(
		belongs_to = "super::order::Entity",
		from = "Column::OrderId",
		to = "super::order::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Order,
}

impl Related<super::gift_card::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::GiftCard.def()
	}
}

impl Related<super::order::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Order.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
	#[sea_orm(entity = "super::gift_card::Entity")]
	GiftCard,
	#[sea_orm(entity = "super::order::Entity")]
	Order,
}
