//! `SeaORM` Entity, @generated by sea-orm-codegen 0.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "idempotency_key")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: String,
	#[sea_orm(unique)]
	pub idempotency_key: String,
	pub created_at: DateTimeWithTimeZone,
	pub locked_at: Option<DateTimeWithTimeZone>,
	pub request_method: Option<String>,
	#[sea_orm(column_type = "JsonBinary", nullable)]
	pub request_params: Option<Json>,
	pub request_path: Option<String>,
	pub response_code: Option<i32>,
	#[sea_orm(column_type = "JsonBinary", nullable)]
	pub response_body: Option<Json>,
	pub recovery_point: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
