//! `SeaORM` Entity, @generated by sea-orm-codegen 0.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "notification")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: String,
	pub event_name: Option<String>,
	pub resource_type: String,
	pub resource_id: String,
	pub customer_id: Option<String>,
	pub to: String,
	#[sea_orm(column_type = "JsonBinary")]
	pub data: Json,
	pub parent_id: Option<String>,
	pub provider_id: Option<String>,
	pub created_at: DateTimeWithTimeZone,
	pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::customer::Entity",
		from = "Column::CustomerId",
		to = "super::customer::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Customer,
	#[sea_orm(
		belongs_to = "Entity",
		from = "Column::ParentId",
		to = "Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	SelfRef,
	#[sea_orm(
		belongs_to = "super::notification_provider::Entity",
		from = "Column::ProviderId",
		to = "super::notification_provider::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	NotificationProvider,
}

impl Related<super::customer::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Customer.def()
	}
}

impl Related<super::notification_provider::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::NotificationProvider.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
	#[sea_orm(entity = "super::customer::Entity")]
	Customer,
	#[sea_orm(entity = "Entity", def = "Relation::SelfRef.def()")]
	SelfRef,
	#[sea_orm(entity = "super::notification_provider::Entity")]
	NotificationProvider,
	#[sea_orm(entity = "Entity", def = "Relation::SelfRef.def().rev()")]
	SelfRefReverse,
}
