//! `SeaORM` Entity, @generated by sea-orm-codegen 0.1.0

use super::sea_orm_active_enums::OrderItemChangeTypeEnum;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "order_item_change")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: String,
	pub created_at: DateTimeWithTimeZone,
	pub updated_at: DateTimeWithTimeZone,
	pub deleted_at: Option<DateTimeWithTimeZone>,
	pub r#type: OrderItemChangeTypeEnum,
	pub order_edit_id: String,
	pub original_line_item_id: Option<String>,
	#[sea_orm(unique)]
	pub line_item_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::line_item::Entity",
		from = "Column::LineItemId",
		to = "super::line_item::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	LineItem2,
	#[sea_orm(
		belongs_to = "super::line_item::Entity",
		from = "Column::OriginalLineItemId",
		to = "super::line_item::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	LineItem1,
	#[sea_orm(
		belongs_to = "super::order_edit::Entity",
		from = "Column::OrderEditId",
		to = "super::order_edit::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	OrderEdit,
}

impl Related<super::order_edit::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::OrderEdit.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
	#[sea_orm(entity = "super::line_item::Entity", def = "Relation::LineItem2.def()")]
	LineItem2,
	#[sea_orm(entity = "super::line_item::Entity", def = "Relation::LineItem1.def()")]
	LineItem1,
	#[sea_orm(entity = "super::order_edit::Entity")]
	OrderEdit,
}
