//! `SeaORM` Entity, @generated by sea-orm-codegen 0.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "price_list_customer_groups")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub price_list_id: String,
	#[sea_orm(primary_key, auto_increment = false)]
	pub customer_group_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::customer_group::Entity",
		from = "Column::CustomerGroupId",
		to = "super::customer_group::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	CustomerGroup,
	#[sea_orm(
		belongs_to = "super::price_list::Entity",
		from = "Column::PriceListId",
		to = "super::price_list::Column::Id",
		on_update = "Cascade",
		on_delete = "Cascade"
	)]
	PriceList,
}

impl Related<super::customer_group::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::CustomerGroup.def()
	}
}

impl Related<super::price_list::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::PriceList.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
	#[sea_orm(entity = "super::customer_group::Entity")]
	CustomerGroup,
	#[sea_orm(entity = "super::price_list::Entity")]
	PriceList,
}
