//! `SeaORM` Entity, @generated by sea-orm-codegen 0.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "product_option_value")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: String,
	pub value: String,
	pub option_id: String,
	pub variant_id: String,
	pub created_at: DateTimeWithTimeZone,
	pub updated_at: DateTimeWithTimeZone,
	pub deleted_at: Option<DateTimeWithTimeZone>,
	#[sea_orm(column_type = "JsonBinary", nullable)]
	pub metadata: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::product_option::Entity",
		from = "Column::OptionId",
		to = "super::product_option::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	ProductOption,
	#[sea_orm(
		belongs_to = "super::product_variant::Entity",
		from = "Column::VariantId",
		to = "super::product_variant::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	ProductVariant,
}

impl Related<super::product_option::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ProductOption.def()
	}
}

impl Related<super::product_variant::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ProductVariant.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
	#[sea_orm(entity = "super::product_option::Entity")]
	ProductOption,
	#[sea_orm(entity = "super::product_variant::Entity")]
	ProductVariant,
}
