//! `SeaORM` Entity, @generated by sea-orm-codegen 0.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "product_variant")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: String,
	pub title: String,
	pub product_id: String,
	#[sea_orm(unique)]
	pub sku: Option<String>,
	#[sea_orm(unique)]
	pub barcode: Option<String>,
	#[sea_orm(unique)]
	pub ean: Option<String>,
	#[sea_orm(unique)]
	pub upc: Option<String>,
	pub inventory_quantity: i32,
	pub allow_backorder: bool,
	pub manage_inventory: bool,
	pub hs_code: Option<String>,
	pub origin_country: Option<String>,
	pub mid_code: Option<String>,
	pub material: Option<String>,
	pub weight: Option<i32>,
	pub length: Option<i32>,
	pub height: Option<i32>,
	pub width: Option<i32>,
	pub created_at: DateTimeWithTimeZone,
	pub updated_at: DateTimeWithTimeZone,
	pub deleted_at: Option<DateTimeWithTimeZone>,
	#[sea_orm(column_type = "JsonBinary", nullable)]
	pub metadata: Option<Json>,
	pub variant_rank: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::claim_item::Entity")]
	ClaimItem,
	#[sea_orm(has_many = "super::line_item::Entity")]
	LineItem,
	#[sea_orm(
		belongs_to = "super::product::Entity",
		from = "Column::ProductId",
		to = "super::product::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Product,
	#[sea_orm(has_many = "super::product_option_value::Entity")]
	ProductOptionValue,
}

impl Related<super::claim_item::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ClaimItem.def()
	}
}

impl Related<super::line_item::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::LineItem.def()
	}
}

impl Related<super::product::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Product.def()
	}
}

impl Related<super::product_option_value::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ProductOptionValue.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
	#[sea_orm(entity = "super::claim_item::Entity")]
	ClaimItem,
	#[sea_orm(entity = "super::line_item::Entity")]
	LineItem,
	#[sea_orm(entity = "super::product::Entity")]
	Product,
	#[sea_orm(entity = "super::product_option_value::Entity")]
	ProductOptionValue,
}
