//! `SeaORM` Entity, @generated by sea-orm-codegen 0.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "return_item")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub return_id: String,
	#[sea_orm(primary_key, auto_increment = false)]
	pub item_id: String,
	pub quantity: i32,
	pub is_requested: bool,
	pub requested_quantity: Option<i32>,
	pub received_quantity: Option<i32>,
	#[sea_orm(column_type = "JsonBinary", nullable)]
	pub metadata: Option<Json>,
	pub reason_id: Option<String>,
	pub note: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::line_item::Entity",
		from = "Column::ItemId",
		to = "super::line_item::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	LineItem,
	#[sea_orm(
		belongs_to = "super::r#return::Entity",
		from = "Column::ReturnId",
		to = "super::r#return::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Return,
	#[sea_orm(
		belongs_to = "super::return_reason::Entity",
		from = "Column::ReasonId",
		to = "super::return_reason::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	ReturnReason,
}

impl Related<super::line_item::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::LineItem.def()
	}
}

impl Related<super::r#return::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Return.def()
	}
}

impl Related<super::return_reason::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ReturnReason.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
	#[sea_orm(entity = "super::line_item::Entity")]
	LineItem,
	#[sea_orm(entity = "super::r#return::Entity")]
	Return,
	#[sea_orm(entity = "super::return_reason::Entity")]
	ReturnReason,
}
