//! `SeaORM` Entity, @generated by sea-orm-codegen 0.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "sales_channel")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: String,
	pub created_at: DateTimeWithTimeZone,
	pub updated_at: DateTimeWithTimeZone,
	pub deleted_at: Option<DateTimeWithTimeZone>,
	pub name: String,
	pub description: Option<String>,
	pub is_disabled: bool,
	#[sea_orm(column_type = "JsonBinary", nullable)]
	pub metadata: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::cart::Entity")]
	Cart,
	#[sea_orm(has_many = "super::order::Entity")]
	Order,
	#[sea_orm(has_many = "super::product_sales_channel::Entity")]
	ProductSalesChannel,
	#[sea_orm(has_one = "super::store::Entity")]
	Store,
}

impl Related<super::cart::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Cart.def()
	}
}

impl Related<super::order::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Order.def()
	}
}

impl Related<super::product_sales_channel::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ProductSalesChannel.def()
	}
}

impl Related<super::store::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Store.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
	#[sea_orm(entity = "super::cart::Entity")]
	Cart,
	#[sea_orm(entity = "super::order::Entity")]
	Order,
	#[sea_orm(entity = "super::product_sales_channel::Entity")]
	ProductSalesChannel,
	#[sea_orm(entity = "super::store::Entity")]
	Store,
}
