[package]
name = "queue"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
# Local
common = { path = "../common" }

crossbeam = { workspace = true }