// DO NOT EDIT THIS FILE
// This file was generated by https://github.com/tacogips/async-graphql-reverse

use sdk::prelude::*;
#[derive(Serialize, Deserialize, Copy, Clone, Debug, Eq, PartialEq)]
pub enum EvaluatorTypeEnum {
	Graaljs,
	Valueparam,
}
#[derive(Serialize, Deserialize, Copy, Clone, Debug, Eq, PartialEq)]
pub enum ForkTypeEnum {
	Differenttask,
	Sametask,
	Sametasksubworkflow,
}
#[derive(Serialize, Deserialize, Copy, Clone, Debug, Eq, PartialEq)]
pub enum IdempotencyStrategyEnum {
	Fail,
	Runningexisting,
}
#[derive(Serialize, Deserialize, Copy, Clone, Debug, Eq, PartialEq)]
pub enum OperationTypeEnum {
	Delete,
	Insert,
	Select,
	Update,
}
#[derive(Serialize, Deserialize, Copy, Clone, Debug, Eq, PartialEq)]
pub enum OrderByEnum {
	Asc,
	Desc,
}
#[derive(Serialize, Deserialize, Copy, Clone, Debug, Eq, PartialEq)]
pub enum RetryLogicEnum {
	Exponentialbackoff,
	Fixed,
	Linearbackoff,
}
#[derive(Serialize, Deserialize, Copy, Clone, Debug, Eq, PartialEq)]
pub enum TaskStatusEnum {
	Canceled,
	Completed,
	Completedwitherrors,
	Failed,
	Failedwithterminalerror,
	Inprogress,
	Scheduled,
	Skipped,
	Timedout,
}
#[derive(Serialize, Deserialize, Copy, Clone, Debug, Eq, PartialEq)]
pub enum TaskTerminationStatusEnum {
	Completed,
	Failed,
	Terminated,
}
#[derive(Serialize, Deserialize, Copy, Clone, Debug, Eq, PartialEq)]
pub enum TaskTypeEnum {
	Buissnessrule,
	Dowhile,
	Dynamic,
	Event,
	Exclusivejoin,
	Forkjoin,
	Forkjoindynamic,
	Getsignedjwt,
	Http,
	Human,
	Inline,
	Join,
	Jsonjqtransform,
	Kafkapublish,
	Setvariable,
	Simple,
	Sqltask,
	Startworkflow,
	Subworkflow,
	Switch,
	Terminatetask,
	Terminateworkflow,
	Updatesecret,
	Updatetask,
	Userdefined,
	Wait,
	Waitforwebhook,
}
#[derive(Serialize, Deserialize, Copy, Clone, Debug, Eq, PartialEq)]
pub enum TimeoutPolicyEnum {
	Alertonly,
	Retry,
	Timedoutwf,
}
