//! `SeaORM` Entity, @generated by sea-orm-codegen 0.1.0

pub mod address;
pub mod analytics_config;
pub mod batch_job;
pub mod cart;
pub mod cart_discounts;
pub mod cart_gift_cards;
pub mod claim_image;
pub mod claim_item;
pub mod claim_item_tags;
pub mod claim_order;
pub mod claim_tag;
pub mod country;
pub mod currency;
pub mod custom_shipping_option;
pub mod customer;
pub mod customer_group;
pub mod customer_group_customers;
pub mod discount;
pub mod discount_condition;
pub mod discount_condition_customer_group;
pub mod discount_condition_product;
pub mod discount_condition_product_collection;
pub mod discount_condition_product_tag;
pub mod discount_condition_product_type;
pub mod discount_regions;
pub mod discount_rule;
pub mod discount_rule_products;
pub mod draft_order;
pub mod fulfillment;
pub mod fulfillment_item;
pub mod fulfillment_provider;
pub mod gift_card;
pub mod gift_card_transaction;
pub mod idempotency_key;
pub mod image;
pub mod invite;
pub mod line_item;
pub mod line_item_adjustment;
pub mod line_item_tax_line;
pub mod money_amount;
pub mod note;
pub mod notification;
pub mod notification_provider;
pub mod oauth;
pub mod onboarding_state;
pub mod order;
pub mod order_discounts;
pub mod order_edit;
pub mod order_gift_cards;
pub mod order_item_change;
pub mod payment;
pub mod payment_collection;
pub mod payment_collection_payments;
pub mod payment_collection_sessions;
pub mod payment_provider;
pub mod payment_session;
pub mod price_list;
pub mod price_list_customer_groups;
pub mod product;
pub mod product_category;
pub mod product_category_product;
pub mod product_collection;
pub mod product_images;
pub mod product_option;
pub mod product_option_value;
pub mod product_sales_channel;
pub mod product_shipping_profile;
pub mod product_tag;
pub mod product_tags;
pub mod product_tax_rate;
pub mod product_type;
pub mod product_type_tax_rate;
pub mod product_variant;
pub mod product_variant_inventory_item;
pub mod product_variant_money_amount;
pub mod publishable_api_key;
pub mod publishable_api_key_sales_channel;
pub mod refund;
pub mod region;
pub mod region_fulfillment_providers;
pub mod region_payment_providers;
pub mod r#return;
pub mod return_item;
pub mod return_reason;
pub mod sales_channel;
pub mod sales_channel_location;
pub mod shipping_method;
pub mod shipping_method_tax_line;
pub mod shipping_option;
pub mod shipping_option_requirement;
pub mod shipping_profile;
pub mod shipping_tax_rate;
pub mod staged_job;
pub mod store;
pub mod store_currencies;
pub mod swap;
pub mod tax_provider;
pub mod tax_rate;
pub mod tracking_link;
pub mod user;
pub fn router(cfg: &mut web::ServiceConfig) {
	cfg.service(
		web::scope("/rest")
			.configure(address::configure)
			.configure(analytics_config::configure)
			.configure(batch_job::configure)
			.configure(cart::configure)
			.configure(cart_discounts::configure)
			.configure(cart_gift_cards::configure)
			.configure(claim_image::configure)
			.configure(claim_item::configure)
			.configure(claim_item_tags::configure)
			.configure(claim_order::configure)
			.configure(claim_tag::configure)
			.configure(country::configure)
			.configure(currency::configure)
			.configure(custom_shipping_option::configure)
			.configure(customer::configure)
			.configure(customer_group::configure)
			.configure(customer_group_customers::configure)
			.configure(discount::configure)
			.configure(discount_condition::configure)
			.configure(discount_condition_customer_group::configure)
			.configure(discount_condition_product::configure)
			.configure(discount_condition_product_collection::configure)
			.configure(discount_condition_product_tag::configure)
			.configure(discount_condition_product_type::configure)
			.configure(discount_regions::configure)
			.configure(discount_rule::configure)
			.configure(discount_rule_products::configure)
			.configure(draft_order::configure)
			.configure(fulfillment::configure)
			.configure(fulfillment_item::configure)
			.configure(fulfillment_provider::configure)
			.configure(gift_card::configure)
			.configure(gift_card_transaction::configure)
			.configure(idempotency_key::configure)
			.configure(image::configure)
			.configure(invite::configure)
			.configure(line_item::configure)
			.configure(line_item_adjustment::configure)
			.configure(line_item_tax_line::configure)
			.configure(money_amount::configure)
			.configure(note::configure)
			.configure(notification::configure)
			.configure(notification_provider::configure)
			.configure(oauth::configure)
			.configure(onboarding_state::configure)
			.configure(order::configure)
			.configure(order_discounts::configure)
			.configure(order_edit::configure)
			.configure(order_gift_cards::configure)
			.configure(order_item_change::configure)
			.configure(payment::configure)
			.configure(payment_collection::configure)
			.configure(payment_collection_payments::configure)
			.configure(payment_collection_sessions::configure)
			.configure(payment_provider::configure)
			.configure(payment_session::configure)
			.configure(price_list::configure)
			.configure(price_list_customer_groups::configure)
			.configure(product::configure)
			.configure(product_category::configure)
			.configure(product_category_product::configure)
			.configure(product_collection::configure)
			.configure(product_images::configure)
			.configure(product_option::configure)
			.configure(product_option_value::configure)
			.configure(product_sales_channel::configure)
			.configure(product_shipping_profile::configure)
			.configure(product_tag::configure)
			.configure(product_tags::configure)
			.configure(product_tax_rate::configure)
			.configure(product_type::configure)
			.configure(product_type_tax_rate::configure)
			.configure(product_variant::configure)
			.configure(product_variant_inventory_item::configure)
			.configure(product_variant_money_amount::configure)
			.configure(publishable_api_key::configure)
			.configure(publishable_api_key_sales_channel::configure)
			.configure(refund::configure)
			.configure(region::configure)
			.configure(region_fulfillment_providers::configure)
			.configure(region_payment_providers::configure)
			.configure(r#return::configure)
			.configure(return_item::configure)
			.configure(return_reason::configure)
			.configure(sales_channel::configure)
			.configure(sales_channel_location::configure)
			.configure(shipping_method::configure)
			.configure(shipping_method_tax_line::configure)
			.configure(shipping_option::configure)
			.configure(shipping_option_requirement::configure)
			.configure(shipping_profile::configure)
			.configure(shipping_tax_rate::configure)
			.configure(staged_job::configure)
			.configure(store::configure)
			.configure(store_currencies::configure)
			.configure(swap::configure)
			.configure(tax_provider::configure)
			.configure(tax_rate::configure)
			.configure(tracking_link::configure)
			.configure(user::configure),
	);
}
